// Code generated by gercmd from auth_mgr.go; DO NOT EDIT.
// 改动请改模块方法上的 export: 标记后重新生成：go generate ./src/mods/

package service

import (
	"noteserver/src/comm"
	"time"
)

// Register 查重并建号，返回账号 ID。手机号已存在时返回 contract.ErrPhoneTaken。
//
// passwordHash 由调用方（HTTP 层）预先算好，见包注释。
func (that *Hub) AuthRegister(gid uint64, uid string, passwordHash string) (string, error) {
	out, err := that.AuthFor(uid).ModInvokeFrom(gid, "AuthMgr", "Register", uid, passwordHash)
	return unwrap[string](out, err, "AuthMgr.Register")
}

// Lookup 取出账号，供 HTTP 层比对密码。
//
// 返回的是 comm.AccountSnap 而不是本模块自己的类型——规范要求跨模块只传
// **Snap。哈希跟着快照一起离开 actor，只是在同一个进程内传递，HTTP 层比对完
// 就丢；换来的是 bcrypt 那几十毫秒不占用事件循环。
func (that *Hub) AuthLookup(gid uint64, uid string) (comm.AccountSnap, error) {
	out, err := that.AuthFor(uid).ModInvokeFrom(gid, "AuthMgr", "Lookup", uid)
	return unwrap[comm.AccountSnap](out, err, "AuthMgr.Lookup")
}

// TouchLogin 记一次登录时间。
//
// 没有返回值，因此是一次**投递即忘**的调用：HTTP 层不等它完成，
// 登录应答不会被这次写拖慢。
//
// 代价是失败没有调用方能接，所以只能在这里自己消化掉。注意**不能 panic**：
// 框架 handleTask 里的 recover 在上报 PhaseInvoke 之后会顺手 Close 掉整个
// actor，为了一次记录登录时间的失败干掉一整个分片，代价完全不成比例。
// 真正会被上报到 DiscardedErrorHandler 的是投递层面的失败（队列满、actor 已关），
// 那类失败本来也不是这里能处理的。
func (that *Hub) AuthTouchLogin(gid uint64, uid string, at time.Time) {
	// 无返回值 = 投递即忘，调用方不等它完成。这里的 error 只可能是投递失败
	// （队列满、actor 已关），而那一类框架已经报给 DiscardedErrorHandler 了，
	// 再返回一次只会让调用方重复处理同一件事。
	_, _ = that.AuthFor(uid).ModInvokeFrom(gid, "AuthMgr", "TouchLogin", uid, at)
}
