// Code generated by gercmd from mailbox_mod.go; DO NOT EDIT.
// 改动请改模块方法上的 export: 标记后重新生成：go generate ./src/mods/

package service

import (
	"noteserver/src/comm"
)

// Push 接收 MailMgr 推过来的完整信箱。
//
// **无返回值**，这是 mgr → mod 唯一的一条边，也是这个模块唯一的写入口。
// 整份替换而不是增量合并：增量要处理乱序、丢包、去重，而信箱最多
// comm.MailKeepLimit 封，整份推的代价完全可以接受。用简单换正确。
func (that *Hub) MailboxPush(gid uint64, uid string, mails []comm.MailSnap) {
	// 无返回值 = 通知，来自别的模块。用户不在线就丢弃，**不创建 actor**。
	loader := that.TryUser(uid)
	if loader == nil {
		return
	}
	defer that.ReleaseUser(uid)

	// 投递失败框架已经报给 DiscardedErrorHandler，这里再返回一次只会让
	// 调用方重复处理同一件事。
	_, _ = loader.ModInvokeFrom(gid, "MailboxMod", "Push", mails)
}

// List 交出当前的信箱视图。
//
// 它**有返回值**，而且这是合规的：调用方是 rut，跑在 gin 的请求协程上，
// 不会被任何模块调用。这条界线就是 mgr↔mod"只通知"与 rut→模块"可以要返回值"
// 的分界。
//
// 数据还没到时不假装成"你没有邮件"：返回 Ready=false，由 rut 去催一次 mgr
// 并回 202。这两种状态在客户端要显示成不同的东西，混成一个就再也分不开。
//
// 注意它**不会**为了"催一下"而调 mgr——那会让这个模块重新长出一条对外调用。
// 催谁、什么时候催是 rut 的事。
func (that *Hub) MailboxList(gid uint64, uid string) (comm.MailBoxSnap, error) {
	// 有返回值 = 请求，来自 rut。actor 不在就建一个。
	loader := that.AcquireUser(uid)
	defer that.ReleaseUser(uid)

	out, err := loader.ModInvokeFrom(gid, "MailboxMod", "List")
	return unwrap[comm.MailBoxSnap](out, err, "MailboxMod.List")
}
