// Code generated by gercmd from mail_mgr.go; DO NOT EDIT.
// 改动请改模块方法上的 export: 标记后重新生成：go generate ./src/mods/

package service

import (
	"noteserver/src/comm"
)

// Send 给某个用户下发一封邮件。运维后台调它。
//
// **不检查用户是否在线，也不检查用户是否存在**：前者正是这个模块做成 Mgr 的原因，
// 后者是运维的责任——在这里查账号会把 mail 分片和 auth 分片耦在一起。
//
// 信箱满时顶掉**最老的一封**而不是拒收：运维下发不该因为用户信箱满了而失败。
//
// 它有返回值，因为调用方是 rut 层（运维后台的 HTTP 请求），不是别的模块。
// 下发完成后顺带把新信箱推给在线的那个用户——那一跳才是模块间的调用，是通知。
func (that *Hub) MailSend(gid uint64, uid string, title string, content string, items []comm.MailItemSnap) (comm.MailSnap, error) {
	out, err := that.ShardFor("MailMgr", uid).ModInvokeFrom(gid, "MailMgr", "Send", uid, title, content, items)
	return unwrap[comm.MailSnap](out, err, "MailMgr.Send")
}

// Fetch 把某个用户的信箱推给他的 MailboxMod。用户上线时、以及 rut 发现视图还
// 没就绪时调它。
//
// **无返回值**：这是一次"你去干件事"的通知，调用方（Hub 或 rut）不关心结果，
// 结果会以 Push 的形式落到用户 actor 上。即使调用方眼下都不是模块，也不该写成
// 带返回值的——那样 rut 要等 mgr 读完存储，而它等的东西自己根本用不上；
// 更要紧的是哪天有模块要调它时，签名已经是错的了。
func (that *Hub) MailFetch(gid uint64, uid string) {
	// 无返回值 = 投递即忘，调用方不等它完成。这里的 error 只可能是投递失败
	// （队列满、actor 已关），而那一类框架已经报给 DiscardedErrorHandler 了，
	// 再返回一次只会让调用方重复处理同一件事。
	_, _ = that.ShardFor("MailMgr", uid).ModInvokeFrom(gid, "MailMgr", "Fetch", uid)
}

// Claim 领取附件，返回领到的道具。**由 rut 直接调用**。
//
// 它**有返回值**，因为这是一次写操作，调用方需要知道到底成没成：领到了什么、
// 还是这封已经领过了、还是压根不存在。这些问题只有权威侧答得准——存储只有 mgr
// 碰得到。让用户侧的 MailboxMod 转发再立刻返回本地快照，等于拿一份没改过的旧
// 数据冒充操作结果，客户端会以为成功了。
//
// "只能领一次"就落在这里：同一个 UID 的所有邮件操作都落在同一个 mgr 分片上，
// 所以这段"读—判断—写"天然串行，不需要任何锁。
//
// 改完之后把新信箱推给在线的那个用户——那一跳才是模块间调用，是单向通知。
func (that *Hub) MailClaim(gid uint64, uid string, mailID string) ([]comm.MailItemSnap, error) {
	out, err := that.ShardFor("MailMgr", uid).ModInvokeFrom(gid, "MailMgr", "Claim", uid, mailID)
	return unwrap[[]comm.MailItemSnap](out, err, "MailMgr.Claim")
}
