// Code generated by gercmd from note_mod.go; DO NOT EDIT.
// 改动请改模块方法上的 export: 标记后重新生成：go generate ./src/mods/

package service

import (
	"noteserver/src/contract"
)

// Add 存一条笔记，返回落库后的完整快照。上传时间由服务端生成，不采信客户端传来的时间。
func (that *Hub) NoteAdd(gid uint64, uid string, content string) (contract.NoteInfo, error) {
	loader := that.AcquireUser(uid)
	defer that.ReleaseUser(uid)
	out, err := loader.ModInvokeFrom(gid, "NoteMod", "Add", content)
	return unwrap[contract.NoteInfo](out, err, "NoteMod.Add")
}

// List 取笔记，按上传时间倒序。首次访问从存储预热缓存，之后直接命中。
func (that *Hub) NoteList(gid uint64, uid string) ([]contract.NoteInfo, error) {
	loader := that.AcquireUser(uid)
	defer that.ReleaseUser(uid)
	out, err := loader.ModInvokeFrom(gid, "NoteMod", "List")
	return unwrap[[]contract.NoteInfo](out, err, "NoteMod.List")
}
