// Code generated by gercmd from bag_mod.go; DO NOT EDIT.
// 改动请改模块方法上的 export: 标记后重新生成。

package player

// hahah
// 增加物品
func (that *PlayerEnt) BagAddItem(itemid int, count int) {
	if _, err := that.GetModloader().ModInvoke("BagMod", "AddItem", itemid, count); err != nil {
		println("BagAddItem err:", err.Error())
	}
}

// hahah
// 删除物品
func (that *PlayerEnt) BagRemoveItem(itemid int, count int, cb func()) {
	if _, err := that.GetModloader().ModInvoke("BagMod", "RemoveItem", itemid, count, cb); err != nil {
		println("BagRemoveItem err:", err.Error())
	}
}
