// Code generated by gercmd from hero_mod.go; DO NOT EDIT.
// 改动请改模块方法上的 export: 标记后重新生成。

package player

// 新增一个英雄
func (that *PlayerEnt) HeroModAddHero(heroid int) {
	if _, err := that.GetModloader().ModInvoke("HeroMod", "AddHero", heroid); err != nil {
		println("HeroModAddHero err:", err.Error())
	}
}
